/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as InternRouteImport } from './routes/intern'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternIndexRouteImport } from './routes/intern.index'
import { Route as InternHistoryRouteImport } from './routes/intern.history'
import { Route as InternCalendarRouteImport } from './routes/intern.calendar'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const InternRoute = InternRouteImport.update({
  id: '/intern',
  path: '/intern',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternIndexRoute = InternIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InternRoute,
} as any)
const InternHistoryRoute = InternHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InternRoute,
} as any)
const InternCalendarRoute = InternCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => InternRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/intern': typeof InternRouteWithChildren
  '/register': typeof RegisterRoute
  '/intern/calendar': typeof InternCalendarRoute
  '/intern/history': typeof InternHistoryRoute
  '/intern/': typeof InternIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/register': typeof RegisterRoute
  '/intern/calendar': typeof InternCalendarRoute
  '/intern/history': typeof InternHistoryRoute
  '/intern': typeof InternIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/intern': typeof InternRouteWithChildren
  '/register': typeof RegisterRoute
  '/intern/calendar': typeof InternCalendarRoute
  '/intern/history': typeof InternHistoryRoute
  '/intern/': typeof InternIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/intern'
    | '/register'
    | '/intern/calendar'
    | '/intern/history'
    | '/intern/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/register'
    | '/intern/calendar'
    | '/intern/history'
    | '/intern'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/intern'
    | '/register'
    | '/intern/calendar'
    | '/intern/history'
    | '/intern/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  InternRoute: typeof InternRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern': {
      id: '/intern'
      path: '/intern'
      fullPath: '/intern'
      preLoaderRoute: typeof InternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern/': {
      id: '/intern/'
      path: '/'
      fullPath: '/intern/'
      preLoaderRoute: typeof InternIndexRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/history': {
      id: '/intern/history'
      path: '/history'
      fullPath: '/intern/history'
      preLoaderRoute: typeof InternHistoryRouteImport
      parentRoute: typeof InternRoute
    }
    '/intern/calendar': {
      id: '/intern/calendar'
      path: '/calendar'
      fullPath: '/intern/calendar'
      preLoaderRoute: typeof InternCalendarRouteImport
      parentRoute: typeof InternRoute
    }
  }
}

interface InternRouteChildren {
  InternCalendarRoute: typeof InternCalendarRoute
  InternHistoryRoute: typeof InternHistoryRoute
  InternIndexRoute: typeof InternIndexRoute
}

const InternRouteChildren: InternRouteChildren = {
  InternCalendarRoute: InternCalendarRoute,
  InternHistoryRoute: InternHistoryRoute,
  InternIndexRoute: InternIndexRoute,
}

const InternRouteWithChildren =
  InternRoute._addFileChildren(InternRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  InternRoute: InternRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
